language: perl
perl:
  - "5.20"
  - "5.18"
  - "5.16"
  - "5.14"
  - "5.12"
  - "5.10"
before_install:
  - cpanm --notest Perl::Tidy
  - cpanm --notest Test::Code::TidyAll 
install: 
  - cpanm --quiet --notest Sparrow
  - cpanm --quiet --installdeps --notest --force --skip-satisfied .
  - cpanm --quiet --notest --skip-satisfied Devel::Cover
  - sparrow plg install catmandu-smoke
script:
  - perl Build.PL && ./Build build && cover -test
  - "export PATH=$PWD/bin && export PERL5LIB=$PWD/lib && sparrow plg run catmandu-smoke"
after_success:
  - cpanm --quiet --notest --skip-satisfied Devel::Cover::Report::Coveralls
  - cover -report coveralls
env: RELEASE_TESTING=1 AUTOMATED_TESTING=1
sudo: false
